# Generated by Django 3.0.3 on 2020-03-06 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(blank=True, max_length=200)),
                ('send_to', models.EmailField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('sendTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
