# Generated by Django 3.0.3 on 2020-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'send To Trash'), ('2', 'Important'), ('3', 'Delete')], default=0, max_length=20),
        ),
    ]
