# Generated by Django 3.0.3 on 2020-03-08 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inbox', '0002_inbox_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='seenTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
