# Generated by Django 2.2.7 on 2020-01-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='assets/uploads/sliders')),
                ('message', models.TextField()),
            ],
        ),
    ]
