# Generated by Django 3.0.3 on 2020-03-10 03:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0008_property_totalfloor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('seen_at', models.DateTimeField(blank=True)),
                ('notify_message', models.TextField()),
                ('notify_for', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='property.Property', verbose_name='Property')),
                ('notify_to', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Notify To')),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
    ]
