# Generated by Django 3.0.2 on 2020-02-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('ad_image', models.ImageField(upload_to='assets/uploads/advertisement')),
                ('ad_placement', models.IntegerField(choices=[('1', 'Property list-Right'), ('2', 'Property list-Bottom'), ('3', 'Property Details-Right'), ('4', 'About-Bottom'), ('5', 'Homepage')])),
            ],
            options={
                'verbose_name_plural': 'Advertisement',
            },
        ),
    ]
