# Generated by Django 3.0.2 on 2020-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_placement',
            field=models.IntegerField(choices=[(1, 'Property list-Right'), (2, 'Property list-Bottom'), (3, 'Property Details-Right'), (4, 'About-Bottom'), (5, 'Homepage')]),
        ),
    ]
