# Generated by Django 3.0.3 on 2020-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0002_auto_20200212_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_placement',
            field=models.IntegerField(choices=[(1, 'Property list-Right'), (2, 'Property list-Bottom'), (3, 'Property Details-Right'), (4, 'About-Bottom'), (5, 'Homepage'), (6, 'Property Search-Right'), (7, 'Property Search-Bottom')]),
        ),
    ]
