# Generated by Django 3.0.3 on 2020-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0003_auto_20200416_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_placement',
            field=models.IntegerField(choices=[(1, 'Property list-Right'), (2, 'Property list-Bottom'), (3, 'Property Details-Right'), (4, 'About-Bottom'), (5, 'Homepage'), (6, 'Property Search-Right'), (7, 'Property Search-Bottom'), (8, 'Homepage Poopup')]),
        ),
    ]
