# Generated by Django 2.2.7 on 2020-01-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='assets/uploads/setup')),
                ('fb', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('insta', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
