# Generated by Django 2.2.7 on 2020-01-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
