# Generated by Django 2.2.7 on 2020-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='master',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='master',
            name='end_time',
            field=models.TimeField(blank=True, default='18:00:00'),
        ),
        migrations.AddField(
            model_name='master',
            name='start_time',
            field=models.TimeField(blank=True, default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='master',
            name='fb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='master',
            name='insta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='master',
            name='logo',
            field=models.ImageField(blank=True, upload_to='assets/uploads/setup'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='master',
            name='title',
            field=models.CharField(blank=True, default='JamsProperty', max_length=200),
        ),
        migrations.AlterField(
            model_name='master',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
