# Generated by Django 3.0.3 on 2020-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20200215_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name_plural': 'Benefits of Ad Post'},
        ),
        migrations.AlterModelOptions(
            name='safetytips',
            options={'verbose_name_plural': 'Safty Tips'},
        ),
        migrations.AlterModelOptions(
            name='termscondition',
            options={'verbose_name_plural': 'Terms & Conditions'},
        ),
    ]
