"""
Django settings for jamsproperty project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q&3ktw1oj!#t$c8co%@e1o5dbf*-!11=e6k&s@7zp=@d=7-8&4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.jamsproperty.com']


# Application definition

INSTALLED_APPS = [
    'Wishlist.apps.WishlistConfig',
    'Notification.apps.NotificationConfig',
    'About.apps.AboutConfig',
    'Advertisement.apps.AdvertisementConfig',
    'Faq.apps.FaqConfig',
    'PropertySettings.apps.PropertysettingsConfig',
    'property.apps.PropertyConfig',
    'testimonial.apps.TestimonialConfig',
    'slider.apps.SliderConfig',
    'Inbox.apps.InboxConfig',
    'Subscriber.apps.SubscriberConfig',
    'UserInfo.apps.UserinfoConfig',
    'location.apps.LocationConfig',
    'master.apps.MasterConfig',
    'material.admin',
    'material.admin.default',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'social_django',
    # 'ckeditor',
]

MATERIAL_ADMIN_SITE = {
    'HEADER': 'Jams Property',  # Admin site header
    'TITLE': 'Jams Property',  # Admin site title
    'FAVICON': 'path/to/favicon',  # Admin site favicon (path to static should be specified)
    # 'MAIN_BG_COLOR': '#056472',  # Admin site main color, css color should be specified
    'MAIN_BG_COLOR': '#4a4a4a',  # Admin site main color, css color should be specified
    'MAIN_HOVER_COLOR': '#4a4a4a',  # Admin site main hover color, css color should be specified
    # 'PROFILE_PICTURE':  'path/to/image',  # Admin site profile picture (path to static should be specified)
    # 'PROFILE_BG':  'path/to/image',  # Admin site profile background (path to static should be specified)
    # 'LOGIN_LOGO':  'path/to/image',  # Admin site logo on login page (path to static should be specified)
    # 'LOGOUT_BG':  'path/to/image',  # Admin site background on login/logout pages (path to static should be specified)
    # 'SHOW_THEMES':  True,  #  Show default admin themes button
    # 'TRAY_REVERSE': True,  # Hide object-tools and additional-submit-line by default
    # 'NAVBAR_REVERSE': True,  # Hide side navbar by default
    # 'SHOW_COUNTS': True, # Show instances counts for each model
    'APP_ICONS': {
        # Set icons for applications(lowercase), including 3rd party apps, {'application_name': 'material_icon_name', ...}
        'sites': 'send',
    },
    'MODEL_ICONS': {
        # Set icons for models(lowercase), including 3rd party models, {'model_name': 'material_icon_name', ...}
        'site': 'contact_mail',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'jamsproperty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',

    'django.contrib.auth.backends.ModelBackend',
)


WSGI_APPLICATION = 'jamsproperty.wsgi.application'

LOGIN_REDIRECT_URL  = 'dashboard'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'faisalsarker$jamsproperty',
        'USER': 'faisalsarker',
        'PASSWORD': 'Sf9546700@#',
        'HOST': 'faisalsarker.mysql.pythonanywhere-services.com',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/assets/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.jamsproperty.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'info@jamsproperty.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = 'Info@2008'


# SOCIAL_AUTH_FACEBOOK_KEY = '760903851106463'
# SOCIAL_AUTH_FACEBOOK_SECRET = 'c590cffe0b49aee338ce25663be39e5b'


SOCIAL_AUTH_FACEBOOK_KEY = '155937612485092'
SOCIAL_AUTH_FACEBOOK_SECRET = 'dc3e8c8237c5653c02872a8a9f16d807'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '611472261761-909c1930rji8o6r53a607t86j4tohtoc.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'j1-4Znox1Nz1rGq6Nm0jUEpB'
