# Generated by Django 3.0.2 on 2020-02-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_auto_20200123_1413'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/uploads/user')),
                ('refference_by', models.IntegerField()),
                ('agent_code', models.CharField(blank=True, max_length=100)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='master.Role')),
            ],
        ),
    ]
