# Generated by Django 3.0.3 on 2020-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_auto_20200215_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
