# Generated by Django 3.0.3 on 2020-04-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_auto_20200408_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='refference_by',
            field=models.CharField(blank=True, default='Null', max_length=20, null=True),
        ),
    ]
