# Generated by Django 3.0.3 on 2020-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_contactus_faq_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
