# Generated by Django 3.0.3 on 2020-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_auto_20200320_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='finencialsupport',
            options={'verbose_name_plural': 'Financial Support'},
        ),
    ]
