# Generated by Django 3.0.3 on 2020-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_auto_20200416_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='assets/uploads/video/company')),
            ],
            options={
                'verbose_name_plural': 'Company Videos',
            },
        ),
    ]
