# Generated by Django 3.0.3 on 2020-04-21 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_companyvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvideo',
            name='image',
        ),
        migrations.AddField(
            model_name='companyvideo',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='assets/uploads/video/company', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
