# Generated by Django 3.0.3 on 2020-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0009_companyvideo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='assets/uploads/video/company', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='companyvideo',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='assets/uploads/video/company', verbose_name='Image'),
        ),
    ]
