# Generated by Django 3.0.3 on 2020-03-07 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytagstype',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/uploads/propertyTag'),
            preserve_default=False,
        ),
    ]
