# Generated by Django 3.0.3 on 2020-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySettings', '0002_propertytagstype_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
