# Generated by Django 3.0.2 on 2020-02-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PropertySettings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_title', models.CharField(blank=True, max_length=200, verbose_name='Property Title')),
                ('Thumbnail', models.ImageField(blank=True, upload_to='assets/uploads/property/thumbnail')),
                ('Price', models.FloatField(blank=True)),
                ('Size', models.FloatField(blank=True)),
                ('Purpose', models.CharField(blank=True, choices=[('1', 'Buy'), ('2', 'Rent'), ('3', 'Sale')], default=0, max_length=20)),
                ('Property_type', models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Featured')], default=0, max_length=20)),
                ('Bed', models.IntegerField(blank=True, default=0)),
                ('Bath', models.IntegerField(blank=True, default=0)),
                ('Kitchen', models.IntegerField(blank=True, default=0)),
                ('Lift', models.IntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('Status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Approved')], default=0, max_length=20)),
                ('Posted_time', models.DateTimeField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.Area')),
                ('Category', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.Category', verbose_name='Category')),
                ('City', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='location.City')),
                ('Facing', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.Facing')),
                ('Posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Property_tag_type', models.ForeignKey(blank=True, default=3, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.PropertyTagsType')),
                ('Unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.Unit', verbose_name='Unit Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.PropertyTag')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('Specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.Specification')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratiings', models.IntegerField(blank=True, default=0)),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_video', models.FileField(blank=True, upload_to='assets/uploads/property/videos', verbose_name='Property Video')),
                ('Property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='assets/uploads/property')),
                ('Property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('ficilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertySettings.Facilities')),
            ],
        ),
    ]
