# Generated by Django 3.0.2 on 2020-02-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Kitchen',
            new_name='Belcony',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Lift',
            new_name='Car_parking',
        ),
    ]
