# Generated by Django 3.0.2 on 2020-02-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200213_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Property_lebel',
            field=models.CharField(blank=True, default='Null', max_length=20),
        ),
    ]
