# Generated by Django 3.0.3 on 2020-03-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_property_lebel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Category',
        ),
    ]
