# Generated by Django 3.0.3 on 2020-03-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200307_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='totalFloor',
            field=models.CharField(blank=True, default='Null', max_length=20),
        ),
    ]
