# Generated by Django 3.0.3 on 2020-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200414_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=20),
        ),
    ]
